/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthAcceptRouteImport } from './routes/_auth/accept'
import { Route as AuthenticatedCampaignIndexRouteImport } from './routes/_authenticated/campaign/index'
import { Route as AuthenticatedCampaignSettingsIndexRouteImport } from './routes/_authenticated/campaign/settings/index'
import { Route as AuthenticatedCampaignSessionsIndexRouteImport } from './routes/_authenticated/campaign/sessions/index'
import { Route as AuthenticatedCampaignQuestsIndexRouteImport } from './routes/_authenticated/campaign/quests/index'
import { Route as AuthenticatedCampaignNpcsIndexRouteImport } from './routes/_authenticated/campaign/npcs/index'
import { Route as AuthenticatedCampaignLocationsIndexRouteImport } from './routes/_authenticated/campaign/locations/index'
import { Route as AuthenticatedCampaignIntegrationsIndexRouteImport } from './routes/_authenticated/campaign/integrations/index'
import { Route as AuthenticatedCampaignCreateIndexRouteImport } from './routes/_authenticated/campaign/create/index'
import { Route as AuthenticatedCampaignSettingsInviteIndexRouteImport } from './routes/_authenticated/campaign/settings/invite/index'
import { Route as AuthenticatedCampaignSessionsSessionIdIndexRouteImport } from './routes/_authenticated/campaign/sessions/$sessionId/index'
import { Route as AuthenticatedCampaignQuestsQuestIdIndexRouteImport } from './routes/_authenticated/campaign/quests/$questId/index'
import { Route as AuthenticatedCampaignNpcsNpcIdIndexRouteImport } from './routes/_authenticated/campaign/npcs/$npcId/index'
import { Route as AuthenticatedCampaignLocationsLocationIdIndexRouteImport } from './routes/_authenticated/campaign/locations/$locationId/index'
import { Route as AuthenticatedCampaignIntegrationsDiscordIndexRouteImport } from './routes/_authenticated/campaign/integrations/discord/index'
import { Route as AuthenticatedCampaignSessionsSessionIdEditRouteImport } from './routes/_authenticated/campaign/sessions/$sessionId/edit'
import { Route as AuthenticatedCampaignQuestsQuestIdEditRouteImport } from './routes/_authenticated/campaign/quests/$questId/edit'
import { Route as AuthenticatedCampaignNpcsNpcIdEditRouteImport } from './routes/_authenticated/campaign/npcs/$npcId/edit'
import { Route as AuthenticatedCampaignLocationsLocationIdEditRouteImport } from './routes/_authenticated/campaign/locations/$locationId/edit'
import { Route as AuthenticatedCampaignIntegrationsDiscordCallbackRouteImport } from './routes/_authenticated/campaign/integrations/discord/callback'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptRoute = AuthAcceptRouteImport.update({
  id: '/_auth/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampaignIndexRoute =
  AuthenticatedCampaignIndexRouteImport.update({
    id: '/campaign/',
    path: '/campaign/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignSettingsIndexRoute =
  AuthenticatedCampaignSettingsIndexRouteImport.update({
    id: '/campaign/settings/',
    path: '/campaign/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignSessionsIndexRoute =
  AuthenticatedCampaignSessionsIndexRouteImport.update({
    id: '/campaign/sessions/',
    path: '/campaign/sessions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignQuestsIndexRoute =
  AuthenticatedCampaignQuestsIndexRouteImport.update({
    id: '/campaign/quests/',
    path: '/campaign/quests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignNpcsIndexRoute =
  AuthenticatedCampaignNpcsIndexRouteImport.update({
    id: '/campaign/npcs/',
    path: '/campaign/npcs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignLocationsIndexRoute =
  AuthenticatedCampaignLocationsIndexRouteImport.update({
    id: '/campaign/locations/',
    path: '/campaign/locations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignIntegrationsIndexRoute =
  AuthenticatedCampaignIntegrationsIndexRouteImport.update({
    id: '/campaign/integrations/',
    path: '/campaign/integrations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignCreateIndexRoute =
  AuthenticatedCampaignCreateIndexRouteImport.update({
    id: '/campaign/create/',
    path: '/campaign/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignSettingsInviteIndexRoute =
  AuthenticatedCampaignSettingsInviteIndexRouteImport.update({
    id: '/campaign/settings/invite/',
    path: '/campaign/settings/invite/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignSessionsSessionIdIndexRoute =
  AuthenticatedCampaignSessionsSessionIdIndexRouteImport.update({
    id: '/campaign/sessions/$sessionId/',
    path: '/campaign/sessions/$sessionId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignQuestsQuestIdIndexRoute =
  AuthenticatedCampaignQuestsQuestIdIndexRouteImport.update({
    id: '/campaign/quests/$questId/',
    path: '/campaign/quests/$questId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignNpcsNpcIdIndexRoute =
  AuthenticatedCampaignNpcsNpcIdIndexRouteImport.update({
    id: '/campaign/npcs/$npcId/',
    path: '/campaign/npcs/$npcId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignLocationsLocationIdIndexRoute =
  AuthenticatedCampaignLocationsLocationIdIndexRouteImport.update({
    id: '/campaign/locations/$locationId/',
    path: '/campaign/locations/$locationId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignIntegrationsDiscordIndexRoute =
  AuthenticatedCampaignIntegrationsDiscordIndexRouteImport.update({
    id: '/campaign/integrations/discord/',
    path: '/campaign/integrations/discord/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignSessionsSessionIdEditRoute =
  AuthenticatedCampaignSessionsSessionIdEditRouteImport.update({
    id: '/campaign/sessions/$sessionId/edit',
    path: '/campaign/sessions/$sessionId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignQuestsQuestIdEditRoute =
  AuthenticatedCampaignQuestsQuestIdEditRouteImport.update({
    id: '/campaign/quests/$questId/edit',
    path: '/campaign/quests/$questId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignNpcsNpcIdEditRoute =
  AuthenticatedCampaignNpcsNpcIdEditRouteImport.update({
    id: '/campaign/npcs/$npcId/edit',
    path: '/campaign/npcs/$npcId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignLocationsLocationIdEditRoute =
  AuthenticatedCampaignLocationsLocationIdEditRouteImport.update({
    id: '/campaign/locations/$locationId/edit',
    path: '/campaign/locations/$locationId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignIntegrationsDiscordCallbackRoute =
  AuthenticatedCampaignIntegrationsDiscordCallbackRouteImport.update({
    id: '/campaign/integrations/discord/callback',
    path: '/campaign/integrations/discord/callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept': typeof AuthAcceptRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join': typeof AuthenticatedJoinRoute
  '/api/$': typeof ApiSplatRoute
  '/campaign/': typeof AuthenticatedCampaignIndexRoute
  '/campaign/create/': typeof AuthenticatedCampaignCreateIndexRoute
  '/campaign/integrations/': typeof AuthenticatedCampaignIntegrationsIndexRoute
  '/campaign/locations/': typeof AuthenticatedCampaignLocationsIndexRoute
  '/campaign/npcs/': typeof AuthenticatedCampaignNpcsIndexRoute
  '/campaign/quests/': typeof AuthenticatedCampaignQuestsIndexRoute
  '/campaign/sessions/': typeof AuthenticatedCampaignSessionsIndexRoute
  '/campaign/settings/': typeof AuthenticatedCampaignSettingsIndexRoute
  '/campaign/integrations/discord/callback': typeof AuthenticatedCampaignIntegrationsDiscordCallbackRoute
  '/campaign/locations/$locationId/edit': typeof AuthenticatedCampaignLocationsLocationIdEditRoute
  '/campaign/npcs/$npcId/edit': typeof AuthenticatedCampaignNpcsNpcIdEditRoute
  '/campaign/quests/$questId/edit': typeof AuthenticatedCampaignQuestsQuestIdEditRoute
  '/campaign/sessions/$sessionId/edit': typeof AuthenticatedCampaignSessionsSessionIdEditRoute
  '/campaign/integrations/discord/': typeof AuthenticatedCampaignIntegrationsDiscordIndexRoute
  '/campaign/locations/$locationId/': typeof AuthenticatedCampaignLocationsLocationIdIndexRoute
  '/campaign/npcs/$npcId/': typeof AuthenticatedCampaignNpcsNpcIdIndexRoute
  '/campaign/quests/$questId/': typeof AuthenticatedCampaignQuestsQuestIdIndexRoute
  '/campaign/sessions/$sessionId/': typeof AuthenticatedCampaignSessionsSessionIdIndexRoute
  '/campaign/settings/invite/': typeof AuthenticatedCampaignSettingsInviteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept': typeof AuthAcceptRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join': typeof AuthenticatedJoinRoute
  '/api/$': typeof ApiSplatRoute
  '/campaign': typeof AuthenticatedCampaignIndexRoute
  '/campaign/create': typeof AuthenticatedCampaignCreateIndexRoute
  '/campaign/integrations': typeof AuthenticatedCampaignIntegrationsIndexRoute
  '/campaign/locations': typeof AuthenticatedCampaignLocationsIndexRoute
  '/campaign/npcs': typeof AuthenticatedCampaignNpcsIndexRoute
  '/campaign/quests': typeof AuthenticatedCampaignQuestsIndexRoute
  '/campaign/sessions': typeof AuthenticatedCampaignSessionsIndexRoute
  '/campaign/settings': typeof AuthenticatedCampaignSettingsIndexRoute
  '/campaign/integrations/discord/callback': typeof AuthenticatedCampaignIntegrationsDiscordCallbackRoute
  '/campaign/locations/$locationId/edit': typeof AuthenticatedCampaignLocationsLocationIdEditRoute
  '/campaign/npcs/$npcId/edit': typeof AuthenticatedCampaignNpcsNpcIdEditRoute
  '/campaign/quests/$questId/edit': typeof AuthenticatedCampaignQuestsQuestIdEditRoute
  '/campaign/sessions/$sessionId/edit': typeof AuthenticatedCampaignSessionsSessionIdEditRoute
  '/campaign/integrations/discord': typeof AuthenticatedCampaignIntegrationsDiscordIndexRoute
  '/campaign/locations/$locationId': typeof AuthenticatedCampaignLocationsLocationIdIndexRoute
  '/campaign/npcs/$npcId': typeof AuthenticatedCampaignNpcsNpcIdIndexRoute
  '/campaign/quests/$questId': typeof AuthenticatedCampaignQuestsQuestIdIndexRoute
  '/campaign/sessions/$sessionId': typeof AuthenticatedCampaignSessionsSessionIdIndexRoute
  '/campaign/settings/invite': typeof AuthenticatedCampaignSettingsInviteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/accept': typeof AuthAcceptRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/campaign/': typeof AuthenticatedCampaignIndexRoute
  '/_authenticated/campaign/create/': typeof AuthenticatedCampaignCreateIndexRoute
  '/_authenticated/campaign/integrations/': typeof AuthenticatedCampaignIntegrationsIndexRoute
  '/_authenticated/campaign/locations/': typeof AuthenticatedCampaignLocationsIndexRoute
  '/_authenticated/campaign/npcs/': typeof AuthenticatedCampaignNpcsIndexRoute
  '/_authenticated/campaign/quests/': typeof AuthenticatedCampaignQuestsIndexRoute
  '/_authenticated/campaign/sessions/': typeof AuthenticatedCampaignSessionsIndexRoute
  '/_authenticated/campaign/settings/': typeof AuthenticatedCampaignSettingsIndexRoute
  '/_authenticated/campaign/integrations/discord/callback': typeof AuthenticatedCampaignIntegrationsDiscordCallbackRoute
  '/_authenticated/campaign/locations/$locationId/edit': typeof AuthenticatedCampaignLocationsLocationIdEditRoute
  '/_authenticated/campaign/npcs/$npcId/edit': typeof AuthenticatedCampaignNpcsNpcIdEditRoute
  '/_authenticated/campaign/quests/$questId/edit': typeof AuthenticatedCampaignQuestsQuestIdEditRoute
  '/_authenticated/campaign/sessions/$sessionId/edit': typeof AuthenticatedCampaignSessionsSessionIdEditRoute
  '/_authenticated/campaign/integrations/discord/': typeof AuthenticatedCampaignIntegrationsDiscordIndexRoute
  '/_authenticated/campaign/locations/$locationId/': typeof AuthenticatedCampaignLocationsLocationIdIndexRoute
  '/_authenticated/campaign/npcs/$npcId/': typeof AuthenticatedCampaignNpcsNpcIdIndexRoute
  '/_authenticated/campaign/quests/$questId/': typeof AuthenticatedCampaignQuestsQuestIdIndexRoute
  '/_authenticated/campaign/sessions/$sessionId/': typeof AuthenticatedCampaignSessionsSessionIdIndexRoute
  '/_authenticated/campaign/settings/invite/': typeof AuthenticatedCampaignSettingsInviteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/join'
    | '/api/$'
    | '/campaign/'
    | '/campaign/create/'
    | '/campaign/integrations/'
    | '/campaign/locations/'
    | '/campaign/npcs/'
    | '/campaign/quests/'
    | '/campaign/sessions/'
    | '/campaign/settings/'
    | '/campaign/integrations/discord/callback'
    | '/campaign/locations/$locationId/edit'
    | '/campaign/npcs/$npcId/edit'
    | '/campaign/quests/$questId/edit'
    | '/campaign/sessions/$sessionId/edit'
    | '/campaign/integrations/discord/'
    | '/campaign/locations/$locationId/'
    | '/campaign/npcs/$npcId/'
    | '/campaign/quests/$questId/'
    | '/campaign/sessions/$sessionId/'
    | '/campaign/settings/invite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/join'
    | '/api/$'
    | '/campaign'
    | '/campaign/create'
    | '/campaign/integrations'
    | '/campaign/locations'
    | '/campaign/npcs'
    | '/campaign/quests'
    | '/campaign/sessions'
    | '/campaign/settings'
    | '/campaign/integrations/discord/callback'
    | '/campaign/locations/$locationId/edit'
    | '/campaign/npcs/$npcId/edit'
    | '/campaign/quests/$questId/edit'
    | '/campaign/sessions/$sessionId/edit'
    | '/campaign/integrations/discord'
    | '/campaign/locations/$locationId'
    | '/campaign/npcs/$npcId'
    | '/campaign/quests/$questId'
    | '/campaign/sessions/$sessionId'
    | '/campaign/settings/invite'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_auth/accept'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/dashboard'
    | '/_authenticated/join'
    | '/api/$'
    | '/_authenticated/campaign/'
    | '/_authenticated/campaign/create/'
    | '/_authenticated/campaign/integrations/'
    | '/_authenticated/campaign/locations/'
    | '/_authenticated/campaign/npcs/'
    | '/_authenticated/campaign/quests/'
    | '/_authenticated/campaign/sessions/'
    | '/_authenticated/campaign/settings/'
    | '/_authenticated/campaign/integrations/discord/callback'
    | '/_authenticated/campaign/locations/$locationId/edit'
    | '/_authenticated/campaign/npcs/$npcId/edit'
    | '/_authenticated/campaign/quests/$questId/edit'
    | '/_authenticated/campaign/sessions/$sessionId/edit'
    | '/_authenticated/campaign/integrations/discord/'
    | '/_authenticated/campaign/locations/$locationId/'
    | '/_authenticated/campaign/npcs/$npcId/'
    | '/_authenticated/campaign/quests/$questId/'
    | '/_authenticated/campaign/sessions/$sessionId/'
    | '/_authenticated/campaign/settings/invite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthAcceptRoute: typeof AuthAcceptRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/accept': {
      id: '/_auth/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AuthAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaign/': {
      id: '/_authenticated/campaign/'
      path: '/campaign'
      fullPath: '/campaign/'
      preLoaderRoute: typeof AuthenticatedCampaignIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/settings/': {
      id: '/_authenticated/campaign/settings/'
      path: '/campaign/settings'
      fullPath: '/campaign/settings/'
      preLoaderRoute: typeof AuthenticatedCampaignSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/sessions/': {
      id: '/_authenticated/campaign/sessions/'
      path: '/campaign/sessions'
      fullPath: '/campaign/sessions/'
      preLoaderRoute: typeof AuthenticatedCampaignSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/quests/': {
      id: '/_authenticated/campaign/quests/'
      path: '/campaign/quests'
      fullPath: '/campaign/quests/'
      preLoaderRoute: typeof AuthenticatedCampaignQuestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/npcs/': {
      id: '/_authenticated/campaign/npcs/'
      path: '/campaign/npcs'
      fullPath: '/campaign/npcs/'
      preLoaderRoute: typeof AuthenticatedCampaignNpcsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/locations/': {
      id: '/_authenticated/campaign/locations/'
      path: '/campaign/locations'
      fullPath: '/campaign/locations/'
      preLoaderRoute: typeof AuthenticatedCampaignLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/integrations/': {
      id: '/_authenticated/campaign/integrations/'
      path: '/campaign/integrations'
      fullPath: '/campaign/integrations/'
      preLoaderRoute: typeof AuthenticatedCampaignIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/create/': {
      id: '/_authenticated/campaign/create/'
      path: '/campaign/create'
      fullPath: '/campaign/create/'
      preLoaderRoute: typeof AuthenticatedCampaignCreateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/settings/invite/': {
      id: '/_authenticated/campaign/settings/invite/'
      path: '/campaign/settings/invite'
      fullPath: '/campaign/settings/invite/'
      preLoaderRoute: typeof AuthenticatedCampaignSettingsInviteIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/sessions/$sessionId/': {
      id: '/_authenticated/campaign/sessions/$sessionId/'
      path: '/campaign/sessions/$sessionId'
      fullPath: '/campaign/sessions/$sessionId/'
      preLoaderRoute: typeof AuthenticatedCampaignSessionsSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/quests/$questId/': {
      id: '/_authenticated/campaign/quests/$questId/'
      path: '/campaign/quests/$questId'
      fullPath: '/campaign/quests/$questId/'
      preLoaderRoute: typeof AuthenticatedCampaignQuestsQuestIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/npcs/$npcId/': {
      id: '/_authenticated/campaign/npcs/$npcId/'
      path: '/campaign/npcs/$npcId'
      fullPath: '/campaign/npcs/$npcId/'
      preLoaderRoute: typeof AuthenticatedCampaignNpcsNpcIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/locations/$locationId/': {
      id: '/_authenticated/campaign/locations/$locationId/'
      path: '/campaign/locations/$locationId'
      fullPath: '/campaign/locations/$locationId/'
      preLoaderRoute: typeof AuthenticatedCampaignLocationsLocationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/integrations/discord/': {
      id: '/_authenticated/campaign/integrations/discord/'
      path: '/campaign/integrations/discord'
      fullPath: '/campaign/integrations/discord/'
      preLoaderRoute: typeof AuthenticatedCampaignIntegrationsDiscordIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/sessions/$sessionId/edit': {
      id: '/_authenticated/campaign/sessions/$sessionId/edit'
      path: '/campaign/sessions/$sessionId/edit'
      fullPath: '/campaign/sessions/$sessionId/edit'
      preLoaderRoute: typeof AuthenticatedCampaignSessionsSessionIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/quests/$questId/edit': {
      id: '/_authenticated/campaign/quests/$questId/edit'
      path: '/campaign/quests/$questId/edit'
      fullPath: '/campaign/quests/$questId/edit'
      preLoaderRoute: typeof AuthenticatedCampaignQuestsQuestIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/npcs/$npcId/edit': {
      id: '/_authenticated/campaign/npcs/$npcId/edit'
      path: '/campaign/npcs/$npcId/edit'
      fullPath: '/campaign/npcs/$npcId/edit'
      preLoaderRoute: typeof AuthenticatedCampaignNpcsNpcIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/locations/$locationId/edit': {
      id: '/_authenticated/campaign/locations/$locationId/edit'
      path: '/campaign/locations/$locationId/edit'
      fullPath: '/campaign/locations/$locationId/edit'
      preLoaderRoute: typeof AuthenticatedCampaignLocationsLocationIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign/integrations/discord/callback': {
      id: '/_authenticated/campaign/integrations/discord/callback'
      path: '/campaign/integrations/discord/callback'
      fullPath: '/campaign/integrations/discord/callback'
      preLoaderRoute: typeof AuthenticatedCampaignIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedCampaignIndexRoute: typeof AuthenticatedCampaignIndexRoute
  AuthenticatedCampaignCreateIndexRoute: typeof AuthenticatedCampaignCreateIndexRoute
  AuthenticatedCampaignIntegrationsIndexRoute: typeof AuthenticatedCampaignIntegrationsIndexRoute
  AuthenticatedCampaignLocationsIndexRoute: typeof AuthenticatedCampaignLocationsIndexRoute
  AuthenticatedCampaignNpcsIndexRoute: typeof AuthenticatedCampaignNpcsIndexRoute
  AuthenticatedCampaignQuestsIndexRoute: typeof AuthenticatedCampaignQuestsIndexRoute
  AuthenticatedCampaignSessionsIndexRoute: typeof AuthenticatedCampaignSessionsIndexRoute
  AuthenticatedCampaignSettingsIndexRoute: typeof AuthenticatedCampaignSettingsIndexRoute
  AuthenticatedCampaignIntegrationsDiscordCallbackRoute: typeof AuthenticatedCampaignIntegrationsDiscordCallbackRoute
  AuthenticatedCampaignLocationsLocationIdEditRoute: typeof AuthenticatedCampaignLocationsLocationIdEditRoute
  AuthenticatedCampaignNpcsNpcIdEditRoute: typeof AuthenticatedCampaignNpcsNpcIdEditRoute
  AuthenticatedCampaignQuestsQuestIdEditRoute: typeof AuthenticatedCampaignQuestsQuestIdEditRoute
  AuthenticatedCampaignSessionsSessionIdEditRoute: typeof AuthenticatedCampaignSessionsSessionIdEditRoute
  AuthenticatedCampaignIntegrationsDiscordIndexRoute: typeof AuthenticatedCampaignIntegrationsDiscordIndexRoute
  AuthenticatedCampaignLocationsLocationIdIndexRoute: typeof AuthenticatedCampaignLocationsLocationIdIndexRoute
  AuthenticatedCampaignNpcsNpcIdIndexRoute: typeof AuthenticatedCampaignNpcsNpcIdIndexRoute
  AuthenticatedCampaignQuestsQuestIdIndexRoute: typeof AuthenticatedCampaignQuestsQuestIdIndexRoute
  AuthenticatedCampaignSessionsSessionIdIndexRoute: typeof AuthenticatedCampaignSessionsSessionIdIndexRoute
  AuthenticatedCampaignSettingsInviteIndexRoute: typeof AuthenticatedCampaignSettingsInviteIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedCampaignIndexRoute: AuthenticatedCampaignIndexRoute,
  AuthenticatedCampaignCreateIndexRoute: AuthenticatedCampaignCreateIndexRoute,
  AuthenticatedCampaignIntegrationsIndexRoute:
    AuthenticatedCampaignIntegrationsIndexRoute,
  AuthenticatedCampaignLocationsIndexRoute:
    AuthenticatedCampaignLocationsIndexRoute,
  AuthenticatedCampaignNpcsIndexRoute: AuthenticatedCampaignNpcsIndexRoute,
  AuthenticatedCampaignQuestsIndexRoute: AuthenticatedCampaignQuestsIndexRoute,
  AuthenticatedCampaignSessionsIndexRoute:
    AuthenticatedCampaignSessionsIndexRoute,
  AuthenticatedCampaignSettingsIndexRoute:
    AuthenticatedCampaignSettingsIndexRoute,
  AuthenticatedCampaignIntegrationsDiscordCallbackRoute:
    AuthenticatedCampaignIntegrationsDiscordCallbackRoute,
  AuthenticatedCampaignLocationsLocationIdEditRoute:
    AuthenticatedCampaignLocationsLocationIdEditRoute,
  AuthenticatedCampaignNpcsNpcIdEditRoute:
    AuthenticatedCampaignNpcsNpcIdEditRoute,
  AuthenticatedCampaignQuestsQuestIdEditRoute:
    AuthenticatedCampaignQuestsQuestIdEditRoute,
  AuthenticatedCampaignSessionsSessionIdEditRoute:
    AuthenticatedCampaignSessionsSessionIdEditRoute,
  AuthenticatedCampaignIntegrationsDiscordIndexRoute:
    AuthenticatedCampaignIntegrationsDiscordIndexRoute,
  AuthenticatedCampaignLocationsLocationIdIndexRoute:
    AuthenticatedCampaignLocationsLocationIdIndexRoute,
  AuthenticatedCampaignNpcsNpcIdIndexRoute:
    AuthenticatedCampaignNpcsNpcIdIndexRoute,
  AuthenticatedCampaignQuestsQuestIdIndexRoute:
    AuthenticatedCampaignQuestsQuestIdIndexRoute,
  AuthenticatedCampaignSessionsSessionIdIndexRoute:
    AuthenticatedCampaignSessionsSessionIdIndexRoute,
  AuthenticatedCampaignSettingsInviteIndexRoute:
    AuthenticatedCampaignSettingsInviteIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthAcceptRoute: AuthAcceptRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
