/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as CampaignNpcsIndexRouteImport } from './routes/campaign/npcs/index'
import { Route as CampaignCreateIndexRouteImport } from './routes/campaign/create/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api.webhooks.clerk'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/campaign/',
  path: '/campaign/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignNpcsIndexRoute = CampaignNpcsIndexRouteImport.update({
  id: '/campaign/npcs/',
  path: '/campaign/npcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCreateIndexRoute = CampaignCreateIndexRouteImport.update({
  id: '/campaign/create/',
  path: '/campaign/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/api/$': typeof ApiSplatRoute
  '/campaign/': typeof CampaignIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/campaign/create/': typeof CampaignCreateIndexRoute
  '/campaign/npcs/': typeof CampaignNpcsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/api/$': typeof ApiSplatRoute
  '/campaign': typeof CampaignIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/campaign/create': typeof CampaignCreateIndexRoute
  '/campaign/npcs': typeof CampaignNpcsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/api/$': typeof ApiSplatRoute
  '/campaign/': typeof CampaignIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/campaign/create/': typeof CampaignCreateIndexRoute
  '/campaign/npcs/': typeof CampaignNpcsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/$'
    | '/campaign/'
    | '/api/webhooks/clerk'
    | '/campaign/create/'
    | '/campaign/npcs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/$'
    | '/campaign'
    | '/api/webhooks/clerk'
    | '/campaign/create'
    | '/campaign/npcs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/$'
    | '/campaign/'
    | '/api/webhooks/clerk'
    | '/campaign/create/'
    | '/campaign/npcs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  CampaignCreateIndexRoute: typeof CampaignCreateIndexRoute
  CampaignNpcsIndexRoute: typeof CampaignNpcsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/campaign'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/npcs/': {
      id: '/campaign/npcs/'
      path: '/campaign/npcs'
      fullPath: '/campaign/npcs/'
      preLoaderRoute: typeof CampaignNpcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/create/': {
      id: '/campaign/create/'
      path: '/campaign/create'
      fullPath: '/campaign/create/'
      preLoaderRoute: typeof CampaignCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  ApiSplatRoute: ApiSplatRoute,
  CampaignIndexRoute: CampaignIndexRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  CampaignCreateIndexRoute: CampaignCreateIndexRoute,
  CampaignNpcsIndexRoute: CampaignNpcsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
