name = "api"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
main = "./build/worker.mjs"

[build]
command = "make build"

[vars]
DISCORD_PUBLIC_KEY="7a52a5c7dbb823c55d7320041568d081a9e520458530a66f18ab6879eba6b17b"
PORT="8000"

[observability.logs]
enabled = true
